export const THEME_COLOR = 'THEME_COLOR';
export const THEME_COLOR_BOOLEAN = 'THEME_COLOR_BOOLEAN';
export const WEB3_OBJECT = 'WEB3_OBJECT';
export const WEB_3_CONNECTED = 'WEB_3_CONNECTED';

// Auth Types
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_DATA_LOADER = 'SET_USER_DATA_LOADER';
export const SET_USER_NFTS = 'SET_USER_NFTS';
export const SET_EXPLORE_NFTS = 'SET_EXPLORE_NFTS';
