export const SET_PROVIDER = "SET_PROVIDER";
export const SET_WALLET_ADDRESS = "SET_WALLET_ADDRESS";
export const DELETE_WALLET_ADDRESS = "DELETE_WALLET_ADDRESS";
export const SET_CONTRACT = "SET_CONTRACT";
export const DELETE_CONTRACT = "DELETE_CONTRACT";
